/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "bg-primary": "#0B0F17",
        "bg-secondary": "#111827",
        "bg-tertiary": "#1F2937",
        surface: "#111A2E",
        "text-primary": "#E5E7EB",
        "text-secondary": "#9CA3AF",
        "text-muted": "#6B7280",
        "border-default": "#243244",
        "border-subtle": "#1B2433",
        success: "#22C55E",
        warning: "#F59E0B",
        danger: "#EF4444",
        info: "#3B82F6",
        "ai-primary": "#6366F1",
        "ai-secondary": "#8B5CF6",
        "ai-glow": "rgba(99, 102, 241, 0.15)",
        "ai-border": "#4F46E5",
        "priority-high": "#EF4444",
        "priority-medium": "#F97316",
        "priority-low": "#22C55E",
        "accent-primary": "#6366F1",
        "accent-hover": "#4F46E5",
        "accent-soft": "rgba(99, 102, 241, 0.12)",
        "fasttrack-active": "#60A5FA",
        "fasttrack-bg": "rgba(59, 130, 246, 0.10)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        sm: "6px",
        md: "10px",
        lg: "14px",
        xl: "18px",
        full: "999px",
      },
    },
  },
  plugins: [],
};
